version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456

  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  mysql_data: